[package]
name = "sval_flatten"
version = "0.0.0"
description = "Value flattening for sval"
edition = "2021"

[dependencies.sval]
path = "../"

[dependencies.sval_buffer]
path = "../buffer"

[dev-dependencies.sval_test]
path = "../test"

[dev-dependencies.sval_derive_macros]
path = "../derive_macros"
